//
// Created by thaeds on 2/11/16.
//

#include "database.h"

Database::Database()
        : records{
        {
                {"903076259",
                        Record(
                                "903076259",
                                "Anthony",
                                "Peterson",
                                231,
                                63,
                                3.666667)
                },
                {"903084074",
                        Record(
                                "903084074",
                                "Richard",
                                "Harris",
                                236,
                                66,
                                3.575758)
                },
                {"903077650",
                        Record(
                                "903077650",
                                "Joe",
                                "Miller",
                                224,
                                65,
                                3.446154)
                },
                {"903083691",
                        Record(
                                "903083691",
                                "Todd",
                                "Collins",
                                218,
                                56,
                                3.892857)
                },
                {"903082265",
                        Record(
                                "903082265",
                                "Laura",
                                "Stewart",
                                207,
                                64,
                                3.234375)
                },
                {"903075951",
                        Record(
                                "903075951",
                                "Marie",
                                "Cox",
                                246,
                                63,
                                3.904762)
                },
                {"903084336",
                        Record(
                                "903084336",
                                "Stephen",
                                "Baker",
                                234,
                                66,
                                3.545455)
                }
        }
        }
{

}
